version: 0.1

phases:
  install:
    commands:
      - npm install
      - npm -g install @angular/cli
  pre_build:
    commands:
      - ng test
  build:
    commands:
      - ng build
  discard-paths: yes
